# docker compose 버전
version: "3"

# 실행하고자 하는 각각의 컨테이너들
services:
    nodejs:
        # swarm mode 에서는 무시됨.
        container_name: nodejs
        image: "nodetest:tag"
        ports:
            - "8080:8080"
        environment:
            - NODE_ENV=development
    nginx:
        container_name: nginx
        image: "nginxtest:sun"
        ports:
            - 80:80
