version: "3"
services:
    # 참고: https://developer88.tistory.com/300
    # nginx:
    #     container_name: nginx
    #     image: "nginxtest:sun"
    #     ports:
    #         - 80:80
    #     volumes:
    #         - ./source/dist:/usr/share/nginx/html
    # nodejs:
    #     container_name: nodejs
    #     image: "nodejs:latest"
    #     ports:
    #         - "8080:8080"
    #     environment:
    #         - NODE_ENV=development

    # 참고: https://medium.com/sjk5766/docker-compose%EB%A1%9C-node-express-%ED%99%98%EA%B2%BD-%EA%B5%AC%EC%B6%95%ED%95%98%EA%B8%B0-7c9ab4544172
