# docker compose 버전
version: "3"

# 실행하고자 하는 각각의 컨테이너들
services:
    proxy:
        image: "nginx:latest"
        container_name: proxy
        ports:
            - "80:80"
        volumes:
#            - ./proxy/nginx.conf:/etc/nginx/nginx.conf
            - ./source/dist:/usr/share/nginx/html
    express:
        build:
            context: ./server
        container_name: express
        expose:
          - "3000"
        volumes:
          - ./server/source:/source
          - /source/node_modules
        restart: "unless-stopped"
